---
- name: Ping
  hosts: linux
  tasks:
  - name: Hostide pingimine
    ansible.builtin.ping:

  - name: OS versioon
    ansible.builtin.debug:
      msg: OS is {{ ansible_distribution }} version {{ ansible_distribution_major_version }}
...